# Netlify configuration file

[build]
  # This tells Netlify to publish the 'dist' folder
  publish = "dist"

# By not specifying a 'command', we tell Netlify to skip the build step.
# It will just deploy the contents of the 'publish' directory. 